### ISSUE TITLE
Time zone conversion

### ISSUE THREAD

**Issue by bruceyang1998** [DavidMoritz/rcv#10]
Symptom: (with Firefox 72.0.1 on Kubuntu 19.10)
Set voting cutoff time to 5 pm EST. Voting did close at 5 pm, but results weren't published. The author replied to the email support request that in his DB the closing time shows up as 11 pm. Perhaps there's an issue with UTC time offset? (lines 35 to 45 in main.js indicates that the program runs with the time zone fixed to CST/CDT)

**Comment by DavidMoritz** [comment]
Yes, the database is in Central time. Thank you for bringing this to my attention. I added the words "Central Time" all over the site to make it clear to users. Also, the bug of the results releasing 6 hours after closing has been resolved as well.
