### ISSUE TITLE
Clicking the duplicate button does nothing

### ISSUE THREAD

**Issue by DanielStevenLewis** [DavidMoritz/rcv#12]
![image](https://user-images.githubusercontent.com/578839/104986142-6e1ef100-59e0-11eb-9e97-cf60d1640405.png)
![image](https://user-images.githubusercontent.com/578839/104986155-770fc280-59e0-11eb-8e3d-5eff70911405.png)
![image](https://user-images.githubusercontent.com/578839/104986171-7e36d080-59e0-11eb-91f8-45b30d3b8a9d.png)
![image](https://user-images.githubusercontent.com/578839/104986184-868f0b80-59e0-11eb-9576-886f0fdbe166.png)
![image](https://user-images.githubusercontent.com/578839/104986220-96a6eb00-59e0-11eb-80b2-5dd8229538d3.png)
![image](https://user-images.githubusercontent.com/578839/104986242-a1fa1680-59e0-11eb-9c5a-faa19d9c1dc4.png)

**Comment by rtil5** [comment]
In addition, the "edit ballot" feature doesn't work, either. No changes are ever saved.

**Comment by DavidMoritz** [comment]
This has been fixed. Thanks!
