### ISSUE TITLE
docker image "Create new ballot" problem

### ISSUE THREAD

**Issue by keck9939** [DavidMoritz/rcv#13]
Following instructions for docker-compose, it built after changing "nodejs-npm to "npm" in Dockerfile-web-app. However, opening the "Create a new ballot" page results in a constant stream of messages on the console:

web-app_1  | [Mon Nov  1 16:38:00 2021] 172.20.0.1:39060 [200]: GET /api/get-key-ballot.php?key=w7nc1ty8xq
web-app_1  | [Mon Nov  1 16:38:00 2021] 172.20.0.1:39060 Closing
web-app_1  | [Mon Nov  1 16:38:00 2021] 172.20.0.1:39064 Accepted

these are repeated  but the key keeps changing. You are unable to create a new shortcode on the new ballot page and if you try to enter a shortcode it says "xxx is already in use"

The problem may be due to unclear instructions for modifying config.php. I've tried several variations, but none of them work. It would be useful if the exact values for 'SERVER' and 'DB' were specified in the instructions or better still, provide a config.php that works under Docker.

Using Docker Desktop 4.1.1 on Windows 10 with the WSL 2 backend.

**Comment by DavidMoritz** [comment]
@kirkhansen might be a good one to address this point. He was the one who wrote the docker-compose instructions.

**Comment by kirkhansen** [comment]
Pushed a PR that should address the issues; creating a ballot and casting and such is working for me with this setup now.
