### ISSUE TITLE
Typo in weighted tie-break method description

### ISSUE THREAD

**Issue by wjt** [DavidMoritz/rcv#19]
On https://rankedchoices.com/create there is the following radio button label:

> **Tie-Break Method:**
> ( ) Random (official)    (🔘) Weighted (factor-in subsequant choices)

That second label should read:

> Weighted (factor in subsequent choices)

I went to submit a pull request but the code in the repo:

https://github.com/DavidMoritz/rcv/blob/acb63a73f7e915553b48b9232503fa9cb4330caf/src/jade/partials/form.jade#L57-L68

doesn't contain this string, nor does it appear in the Git history, so I guess that the code running on https://rankedchoices.com/ has a diff to this repo.

**Comment by DavidMoritz** [comment]
Yes, the code in the live site has drifted away from the original source. I've fixed the typo in the live site. Thank you!
