### ISSUE TITLE
Updating ballot choices is not reflected in UI

### ISSUE THREAD

**Issue by dinoboy197** [DavidMoritz/rcv#21]
I'm creating a ballot with multiple entries (on https://rankedchoices.com/), and after editing the entries list, I cannot see the updated list of entries. I'm very excited about this tool and am hoping this is something easy to fix! This is important because I need to update the candidate list before the final election, and not seeing an up to date list makes this impossible.

How to replicate:
1. Login
2. Create a new ballot (I used default values except for three positions to be elected)
3. Add five candidates.
4. Click submit all entries.
5. Click Profile in top nav bar.
6. Click edit ballot link next to new ballot
7. Click entries radio button
8. See the five candidates that were previous edited
9. Remove two candidates and replace them with two new, different ones
10. Click submit all entries once more
11. Click profile in top nav bar.
12. Click edit ballot link next to the new ballot
13. Click entries radio button

At this point, I see the _original_ list of candidates, not the _new_ list that I saved in step 10.

Please let me know if there is something else that I should be doing to see the updated list of entries in the entry list.

**Comment by DavidMoritz** [comment]
Hello Taylor!

I'm trying to recreate the issue, and I think I was able to do it, but something you didn't mention:

Did you test out voting on the ballot in question? If so, did it have the new set of entries?

I agree that there's a bug, but I am trying to determine to what extent. When I tested it, it seemed like I had the new entries on the vote screen, but not on the profile -> edit screen. ODD!!

Anyway, please email me back so I can get this resolved quickly.

Thanks for using the app!

PS. I went to your website (https://taylor.raack.info/) and tried to use the contact form. It tells me to enter a reCAPTCHA but none is visible. Just thought I'd let you know!

**Comment by dinoboy197** [comment]
Hi David! Thanks for such a quick fix. I did verify the new behavior just now and editing and viewing entries work as expect. Much appreciated! :fireworks: 

Also, thanks for pointing out the issue on my personal website. I'll need to fix up that web form. Cheers!
