### ISSUE TITLE
Poll owner to see results before they are released

### ISSUE THREAD

**Issue by szecsi** [DavidMoritz/rcv#22]
Great app.
Is it possible to hide the results from voters, but let the organizers see how voting is progressing before the vote cutoff?

**Comment by DavidMoritz** [comment]
Thanks!

Yes, it is possible! If you create a profile, then you can see the results before released while you are logged in.

Let me know if that works for you!

**Comment by szecsi** [comment]
It did register, but it did not work. After you said it should, I realized it must have something to do with cookies, so I clicked "remember me" on the login page, and now it works. Thank you very much!
